language: node_js
node_js:
  - "8"
services:
  - xvfb
dist: trusty
addons:
  chrome: stable
before_install:
  - echo "before install"
  - CHROMEDRIVER_VERSION=LATEST_80 npm install chromedriver --save-dev
  - echo "npm setup done"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9922 http://localhost &
  - echo "after install"
script:
  - xvfb-run npm test

